# Dockerfile.prod.frontend
FROM node:18

WORKDIR /app

# Copier le code React
COPY ./frontend /app

# Installer les dépendances et build pour prod
RUN npm install
RUN npm run build

# Optionnel : servir via un serveur HTTP léger (serve ou nginx)
# Ex: npm install -g serve && CMD ["serve", "-s", "build", "-l", "3000"]
